[platformio]
src_dir = MultimetruSiemens

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
src_dir = MultimetruSiemens
build_flags = -Iinc
lib_extra_dirs = src
monitor_speed = 115200
upload_speed = 115200